#!/bin/bash

. vars.conf
output="workflows/auto-builder.yml"

[[ -z ${APP_VERSION_LINK} ]] &&
	APP_VERSION_LINK='$(curl -sL "https://api.github.com/repos/hydazz/docker-'${DOCKERHUB_IMAGE}'/releases/latest" | jq -r \x27.tag_name\x27)'
[[ -z ${TAGS} ]] &&
	TAGS="latest"
[[ -z ${LATEST} ]] &&
	LATEST="latest"

# setup
echo '# This file is automatically generated

name: Auto Builder CI

on:
  workflow_dispatch:
  repository_dispatch:' >${output}
[[ -n ${BUILD_SCHEDULE} ]] &&
	echo '  schedule:
    - cron: "'"${BUILD_SCHEDULE}"'"' >>${output}
[[ ${ON_RELEASE} == "true" ]] &&
	echo '  release:
    types:
      - released' >>${output}
echo '
jobs:' >>${output}
for tag in ${TAGS}; do
	echo '  '"${BASE_OS}"'-'"${tag/./-}"':
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: '"${BRANCH}"'
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        id: buildx

      - name: Docker Login
        uses: docker/login-action@v1
        with:
          username: vcxpz
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Github Login
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"' >>${output}
	if [[ -n ${RELEASE_VERSION_COMMAND} ]] && [ ${LATEST} == "${tag}" ]; then
		echo '
      - name: Check For Updates
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |' >>${output}
		echo -e '          VERSION='"${RELEASE_VERSION_COMMAND}"'' >>${output}
		echo -e '          OLD_VERSION=$(curl -sL "https://api.github.com/repos/hydazz/docker-'"${DOCKERHUB_IMAGE}"'/releases/latest" | jq -r \x27.tag_name\x27)' >>${output}
		echo "          printf '{
               \"tag_name\": \"'\${VERSION}'\",
               \"target_commitish\": \"'\${main}'\",
               \"name\": \"'\${VERSION}'\",
               \"body\": \"Upgrading "${BEAUTY_NAME}" '\${OLD_VERSION}' to '\${VERSION}'\",
               \"draft\": false,
               \"prerelease\": false
          }' >releasebody.json
          curl -H \"Authorization: token \${TOKEN}\" -X POST https://api.github.com/repos/hydazz/docker-${DOCKERHUB_IMAGE}/releases -d @releasebody.json
          rm releasebody.json" >>${output}
	fi
	if [ "${LATEST}" == "${tag}" ]; then
		echo '
      - name: Build The Docker Image Locally
        run: |
          docker buildx build \
            --platform=amd64 \
            --output "type=docker" \
            --build-arg BUILD_DATE="$(date +%Y-%m-%d)" \' >>${output}
		[[ ${VERSIONING} == "true" ]] &&
			echo -e '            --build-arg VERSION='"${APP_VERSION_LINK}"' \' >>${output}
		if [[ -n ${BUILD_ARGS} ]]; then
			echo "${BUILD_ARGS}" | while read -r i; do
				echo '            '"${i}"' \' >>${output}
			done
		fi
		[[ -n ${APP_BRANCH} ]] &&
			echo '            --build-arg BRANCH="'"${APP_BRANCH}"'" \' >>${output}
		echo '            --tag vcxpz/ci-build:ci-build \' >>${output}
		[[ ! ${tag} == "latest" ]] &&
			echo '            --build-arg TAG='"${tag}"' \' >>${output}
		echo '            --file Dockerfile .' >>${output}
		[[ -n ${TEST_SEARCH} ]] &&
			echo '
      - name: Test The Docker Image
        run: |
          export TEST_SEARCH="'"${TEST_SEARCH}"'"
          curl -sSL https://raw.githubusercontent.com/hydazz/docker-utils/main/docker/docker-ci.sh | bash' >>${output}
	fi
	echo '
      - name: Build And Push The Docker Image
        run: |
          docker buildx build \
            --platform='"${PLATFORMS}"' \
            --output "type=image,push=true" \' >>${output}
	[[ ! ${tag} == "latest" ]] &&
		echo '            --build-arg TAG='"${tag}"' \' >>${output}
	echo '            --build-arg BUILD_DATE="$(date +%Y-%m-%d)" \' >>${output}
	[[ ${VERSIONING} == "true" ]] &&
		echo -e '            --build-arg VERSION='"${APP_VERSION_LINK}"' \' >>${output}
	if [[ -n ${BUILD_ARGS} ]]; then
		echo "${BUILD_ARGS}" | while read -r i; do
			echo '            '"${i}"' \' >>${output}
		done
	fi
	[[ -n ${APP_BRANCH} ]] &&
		echo '            --build-arg BRANCH="'"${APP_BRANCH}"'" \' >>${output}

	if [ "${LATEST}" == "${tag}" ]; then
		[[ ${tag} != "latest" ]] &&
			echo '            --tag vcxpz/'"${DOCKERHUB_IMAGE}"':latest \' >>${output}
		[[ ${VERSIONING} == "true" ]] &&
			echo -e '            --tag vcxpz/'"${DOCKERHUB_IMAGE}"':'"${APP_VERSION_LINK}"' \' >>${output}
	elif [ ${VERSIONING} == "true" ]; then
		echo -e '            --tag vcxpz/'"${DOCKERHUB_IMAGE}"':'"${tag}"'-'"${APP_VERSION_LINK}"' \' >>${output}
	fi
	echo '            --tag vcxpz/'"${DOCKERHUB_IMAGE}"':'"${tag}"' \
            --file Dockerfile .' >>${output}

	if [[ ${LATEST} == "${tag}" ]]; then
		echo '
      - name: Get New Package Versions From Image
        run: |
          docker run --rm --entrypoint /bin/sh -v ${PWD}:/tmp vcxpz/ci-build:ci-build -c '\''\' >>${output}

		[[ ${BASE_OS} == "alpine" ]] &&
			echo '            apk info -v | sort >/tmp/package_versions.txt'\''' >>${output}

		[[ ${BASE_OS} == "ubuntu" ]] &&
			echo '            apt list -qq --installed | sed "s#/.*now ##g" | cut -d" " -f1 | sort >/tmp/package_versions.txt'\''' >>${output}

		echo '
      - name: Commit And Push Changes To Github
        run: |
          git add -A
          git commit -m "Bot Updating Files" || true
          git push || true

      - name: Sync README.md With Docker Hub
        uses: peter-evans/dockerhub-description@v2
        with:
          username: vcxpz
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: '"vcxpz/${DOCKERHUB_IMAGE}"'' >>${output}

		[[ -n ${IMAGES} ]] &&
			echo "
      - name: Trigger Images
        env:
          TOKEN: \${{ secrets.TOKEN }}
        run: |
          . .github/vars.conf
          for i in \${IMAGES}; do
          	echo \"Triggering build for \${i}\"
          	curl \\
          		-H \"Accept: application/vnd.github.everest-preview+json\" \\
          		-H \"Authorization: token \${TOKEN}\" \\
          		--request POST \\
          		--data '{\"event_type\": \"Auto Trigger\"}' \\
          		https://api.github.com/repos/hydazz/docker-\${i}/dispatches
          done" >>${output}
	fi
	echo "" >>${output}
done
